version: 2.1 

orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11
  
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          path: ./Dockerfile
          repo: 556789283657.dkr.ecr.ap-southeast-1.amazonaws.com/test-deploy
          tag: latest
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run the deployment job once the build and push image job has completed
          family: 'test-deploy'
          cluster-name: 'test-deploy'
          container-image-name-updates: 'container=test-deploy,tag=latest'
